#Домашнє завдання до тем apply(), groupby(), pivot_table()

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [1]:
import pandas as pd
df = pd.read_csv('../data/supermarket_sales.csv')
type(df)

pandas.core.frame.DataFrame

1. Дослідимо, який філіал супермаркету ('Branch') є найприбутковішим. Для цього знайдіть сумарний прибуток за кожним філіалом і виявіть, який філіал має найвищий.

In [6]:
df.groupby('Branch')['Total'].sum().sort_values(ascending=False)

Branch
C    110568.7065
A    106200.3705
B    106197.6720
Name: Total, dtype: float64

2. В якому місті знайходиться філіал з найвищим прибутком? Може в тому місці нам розмітисти ще один магазин.  
Знайдіть відповідь за допомогою функціоналу Pandas.

In [23]:
df.loc[df['Branch'] == 'C', 'City'].unique()

array(['Naypyitaw'], dtype=object)

3.1. Створіть зводну таблицю, яка покаже, скільки покупок (інвойсів) було зроблено в кожній з філій (`Branch`) за різними категоріями товарів. Запишіть таблицю в змінну `invoices_by_category` і виведіть змінну на екран.
Ця таблиця допоможе проаналізувати, в якій філії купують найбільше товарів кожної з категорій.

In [26]:
invoices_by_category = pd.pivot_table(df, index='Branch', columns='Product line', values='Invoice ID', aggfunc='count')

In [27]:
invoices_by_category

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Branch,,,,,,
A,60,51,58,47,65,59
B,55,62,50,53,50,62
C,55,65,66,52,45,45

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1rueAdko6S3UxIHGtojetTxlES-EyM6Yb)

3.2. Викристовуючи змінну `invoices_by_category` дайте відповідь програмно (тобто значення треба не просто знайти очима, а вивести за допомогою коду), в якому філіалі магазину (`Branch`) найбільше інвойсів із покупкою товарів категорії "Електронні аксесуари" (`Electronic accessories`)?

In [31]:
invoices_by_category['Electronic accessories'].idxmax()

'A'

4-6. **Творче завдання на розвиток аналітичного мислення**

Крок 1. Сформулюйте ТРИ питання (гіпотези) до наявних даних, які допомогли б вам зрозуміти, які користувачі що, де та коли найбільше/найменше купують, аби дати на основі цих гіпотез рекомендації бізнесу. Звісно питання мають бути не тими, на які ми вже відповіли в завданнях модулю.

Крок 2. Знайдіть відповіді на свої питання з допомогою функціоналу pandas.

Крок 3. Напишіть, як відповідь на це питання може бути використана для прийняття бізнес рішень.   
   
 Питання можуть бути будь-якої складності, але їх має бути 3. Кожне питання оцінюється як 1 завдання. Без виконання цього завдання ДЗ не приймається. Якщо є питання щодо виконання - пишіть у чат 🙌

1. У вихідні дні клієнти купують менше/більше, ніж у будні. Пропоную запровадити акції у дні коли кількість покупок менша (Пн, Нд)
2. Які категорії купують найбільше у вихідні. Пропоную заохочувати відвідувачів на додаткові покупки у категоріях з меншим попитом, контролювати запаси  популярних товарів (збільшити).
3. Які категорії товарів формують найбільший прибуток по філіалах. Це допоможе зрозуміти локальний попит. Допомагає оптимізувати асортимент товарів.

In [35]:
df['Date'] = pd.to_datetime(df['Date'])
df['weekday'] = df['Date'].dt.day_name()
df.groupby('weekday')['Total'].agg(['count', 'mean']).sort_values(by='count', ascending=False)

           count        mean
weekday
Saturday     164  342.200058
Tuesday      158  325.836997
Wednesday    143  305.812133
Friday       139  316.016838
Thursday     138  328.617739
Sunday       133  334.269868
Monday       125  303.192624

In [36]:
weekend_df = df[df['weekday'].isin(['Saturday', 'Sunday'])]
weekend_df['Product line'].value_counts(normalize=True)

Product line
Home and lifestyle        0.188552
Fashion accessories       0.185185
Food and beverages        0.181818
Sports and travel         0.175084
Electronic accessories    0.158249
Health and beauty         0.111111
Name: proportion, dtype: float64

In [45]:
profit_by_category = df.groupby(['Branch', 'Product line'])['gross income'].sum().reset_index()
top3_profit = profit_by_category.sort_values(['Branch', 'gross income'], ascending=[True, False]).groupby('Branch').head(3)

print(top3_profit)

   Branch            Product line  gross income
4       A      Home and lifestyle     1067.4855
5       A       Sports and travel      922.5095
0       A  Electronic accessories      872.2435
11      B       Sports and travel      951.8190
9       B       Health and beauty      951.4600
10      B      Home and lifestyle      835.6745
14      C      Food and beverages     1131.7550
13      C     Fashion accessories     1026.6700
12      C  Electronic accessories      903.2845

###